name: Export and Push Results to Demo Branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour, adjust as needed

jobs:
  export-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@v4
        with:
          ref: demo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install sqlite3

      - name: Run export_html.py
        run: python export_html.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/results/opportunities.html
          git commit -m "Update opportunities.html [auto]" || echo "No changes to commit"
          git push origin demo
